export class CourseRegistrationModel {
  nome: string = '';
  telefone: string = '';
  email: string = '';
  matricula: string = '';
  rg_numero: string = '';
  rg_orgao_emissor: string = '';
  rg_uf_emissao: string = '';
  cpf: string = '';
  endereco_rua: string = '';
  endereco_numero: string = '';
  endereco_complemento: string = '';
  endereco_bairro: string = '';
  endereco_cidade: string = '';
  endereco_estado: string = '';
  endereco_cep: string = '';
  pais_origem: string = '';
  estado_origem: string = '';
  cidade_origem: string = '';
  genero: string = '';
  estado_civil: string = '';
  possui_deficiencia: boolean = false;
  data_nascimento: string = '';
  tipo_deficiencia: string = '';
  pais_residencia: string = '';
}
